[package]
name = "portableweb-viewer"
version = "0.1.0"
description = "PortableWeb — native .pweb bundle viewer"
authors = ["Omprakash Selvaraj"]
license = "MIT"
repository = "https://github.com/portableweb/viewer"
edition = "2021"
rust-version = "1.77.2"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zip = "2"
uuid = { version = "1", features = ["v4"] }
mime_guess = "2"

[profile.release]
panic = "abort"
codegen-units = 1
opt-level = "s"
lto = true
strip = true
